on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version'
        required: true
        default: '2021.X.Y'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Run Build
        run: |
          mvn --batch-mode versions:set -DnewVersion=${RELEASE_VERSION} -DgenerateBackupPoms=false
          mvn --batch-mode deploy
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@irof.me"
          git add .
          git commit -am "RELEASE ${RELEASE_VERSION}"
          git tag ${RELEASE_VERSION}
          git push origin main ${RELEASE_VERSION}
        env:
          MAVEN_USERNAME: rR7y2eCS
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          RELEASE_VERSION: ${{ github.event.inputs.version }}
